language: php
php:
  - 5.6
before_script:
    - echo 'extension = mcrypt.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'extension = php_openssl.dll' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - cd src
    - cp .env.example .env
    - composer install
