language: php
php:
  - 5.6
  - nightly

before_script:
    - echo 'extension = mcrypt.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'extension = php_openssl.dll' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - cp .env.example .env
    - composer install
